- src/hotspot/cpu/riscv/nativeInst_riscv.hpp
- src/hotspot/cpu/riscv/vtableStubs_riscv.cpp
Backport of [JDK-8290496](https://bugs.openjdk.java.net/browse/JDK-8290496). Applies cleanly.
Build without --disable-warnings-as-errors after this fix passed on unmatched board with GCC11.
---------
* [JDK-8290496](https://bugs.openjdk.org/browse/JDK-8290496): riscv: Fix build warnings-as-errors with GCC 11
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u pull/2/head:pull/2` \
`$ git checkout pull/2`
`$ git checkout pull/2` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u pull/2/head`
</details>
`$ git pr checkout 2`
View PR using the GUI …
> 8290496: riscv: Fix build warnings-as-errors with GCC 11

- test/hotspot/jtreg/compiler/runtime/TestConstantsInError.java
Please review this backport to riscv-port-jdk17u. Backport of [JDK-8290164](https://bugs.openjdk.org/browse/JDK-8290164).
Since jdk17u does not have the patch [JDK-8280473](https://bugs.openjdk.java.net/browse/JDK-8280473), there will be one less `if` to modify.
Testing:
- compiler/runtime/TestConstantsInError.java passed on qemu and unmacthed.
---------
* [JDK-8290164](https://bugs.openjdk.org/browse/JDK-8290164): compiler/runtime/TestConstantsInError.java fails on riscv
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u pull/3/head:pull/3` \
`$ git checkout pull/3`
`$ git checkout pull/3` \
`$ git pull …
> 8290164: compiler/runtime/TestConstantsInError.java fails on riscv

- src/hotspot/cpu/riscv/frame_riscv.hpp
- src/hotspot/cpu/riscv/riscv.ad
- src/hotspot/cpu/riscv/stubGenerator_riscv.cpp
- src/hotspot/cpu/riscv/vmreg_riscv.cpp
Please review this backport to riscv-port-jdk17u. Backport of [JDK-8293100](https://bugs.openjdk.org/browse/JDK-8293100).
The original patch cannot be directly applied because of the line number, but there are no other additional changes.
Testing:
- vmTestbase/nsk/stress/jni/jnistress002.java passed on qemu and unmacthed.
- all tier1 passed on unmacthed (release).
---------
* [JDK-8293100](https://bugs.openjdk.org/browse/JDK-8293100): RISC-V: Need to save and restore callee-saved FloatRegisters in StubGenerator::generate_call_stub
* [Vladimir Kempik](https://openjdk.org/census#vkempik) (@VladimirKempik - **Reviewer**)
* [Xiaolin Zheng](https://openjdk.org/census#xlinzheng) (@zhengxiaolinX - no project role)
* [Ludovic …
> 8293100: RISC-V: Need to save and restore callee-saved FloatRegisters in StubGenerator::generate_call_stub

- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
Backport of [JDK-8285437](https://bugs.openjdk.java.net/browse/JDK-8285437). Applies cleanly.
Testing:
- A normal springboot-helloworld program using -XX:+VerifyOops passed on qemu and unmacthed.
---------
* [JDK-8285437](https://bugs.openjdk.org/browse/JDK-8285437): riscv: Fix MachNode size mismatch for MacroAssembler::verify_oops*
* [Xiaolin Zheng](https://openjdk.org/census#xlinzheng) (@zhengxiaolinX - no project role)
* [Ludovic Henry](https://openjdk.org/census#luhenry) (@luhenry - no project role)
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u pull/5/head:pull/5` \
`$ git checkout pull/5` …
> 8285437: riscv: Fix MachNode size mismatch for MacroAssembler::verify_oops*

- src/hotspot/cpu/riscv/c1_Runtime1_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/nativeInst_riscv.cpp
- src/hotspot/cpu/riscv/templateInterpreterGenerator_riscv.cpp
Backport of [JDK-8294083](https://bugs.openjdk.org/browse/JDK-8294083). 
Compared to the original patch, the addition of including the corresponding header (gc/shared/collectedHeap.hpp) fix the invalid use of incomplete type 'class CollectedHeap' as follows:
```
=== Output from failing command(s) repeated here ===
* For target hotspot_variant-minimal_libjvm_objs_c1_Runtime1_riscv.o:
/home/zifeihan/riscv-port-jdk17u/src/hotspot/cpu/riscv/c1_Runtime1_riscv.cpp: In static member function 'static OopMapSet* Runtime1::generate_code_for(Runtime1::StubID, StubAssembler*)':
/home/zifeihan/riscv-port-jdk17u/src/hotspot/cpu/riscv/c1_Runtime1_riscv.cpp:675:41: error: invalid use of incomplete type 'class CollectedHeap'
675 |             !UseTLAB && …
```
> 8294083: RISC-V: Minimal build failed with --disable-precompiled-headers

- src/hotspot/cpu/riscv/riscv.ad
Backport of [JDK-8296771](https://bugs.openjdk.org/browse/JDK-8296771). Applies cleanly. 
By the way, we can directly use` compiler/types/TestSubTypeCheckMacroTrichotomy.java` to reproduce the bad ad file error.
Testing:
- compiler/types/TestSubTypeCheckMacroTrichotomy.java passed on qemu/unmatched (fastdebug).
---------
* [JDK-8296771](https://bugs.openjdk.org/browse/JDK-8296771): RISC-V: C2: assert(false) failed: bad AD file
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u pull/8/head:pull/8` \
`$ git checkout pull/8`
`$ git checkout pull/8` \
`$ git pull …
> 8296771: RISC-V: C2: assert(false) failed: bad AD file

- src/hotspot/cpu/riscv/riscv_v.ad
Backport of [JDK-8287970](https://bugs.openjdk.org/browse/JDK-8287970). compared with the original patch, there is less to add Op_PopCountVL to the list of unsupported vectors.
Note that the vector operation VectorOperations.BIT_COUNT has not been introduced in this version, so even if the node Op_PopCountVI exists, it will not cause the test case to fail. Also, the node Op_PopCountVL has not been introduced in this version, so there is no need to add this node to the list of unsupported vectors.
Testing:
- test/jdk/jdk/incubator/vector (release/fastdebug on qemu with UseRVV)
---------
* [JDK-8287970](https://bugs.openjdk.org/browse/JDK-8287970): riscv: …
> 8287970: riscv: jdk/incubator/vector/*VectorTests failing

- src/hotspot/cpu/riscv/c1_LIRGenerator_riscv.cpp
- test/hotspot/jtreg/compiler/floatingpoint/TestLibmIntrinsics.java
Backport of [JDK-8295926](https://bugs.openjdk.org/browse/JDK-8295926). Applies cleanly.
Case test/hotspot/jtreg/compiler/floatingpoint/TestLibmIntrinsics.java failed before this patch.
Testing:
- test/hotspot/jtreg/compiler/floatingpoint/TestLibmIntrinsics.java passed on qemu and unmatched.
---------
* [JDK-8295926](https://bugs.openjdk.org/browse/JDK-8295926): RISC-V: C1: Fix LIRGenerator::do_LibmIntrinsic
* [Xiaolin Zheng](https://openjdk.org/census#xlinzheng) (@zhengxiaolinX - no project role)
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u pull/10/head:pull/10` \
`$ git checkout pull/10` …
> 8295926: RISC-V: C1: Fix LIRGenerator::do_LibmIntrinsic

- src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
- src/hotspot/cpu/riscv/c1_MacroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
- src/hotspot/cpu/riscv/methodHandles_riscv.cpp
- src/hotspot/cpu/riscv/riscv.ad
- src/hotspot/cpu/riscv/sharedRuntime_riscv.cpp
- src/hotspot/cpu/riscv/stubGenerator_riscv.cpp
Backport of [JDK-8296448](https://bugs.openjdk.org/browse/JDK-8296448).
Compared to the original patch, 17u does not have the patches [JDK-8295457](https://bugs.openjdk.org/browse/JDK-8295457) and [JDK-8293290](https://bugs.openjdk.org/browse/JDK-8293290), so some parameters will be slightly different.
The same problem was reproduced using the same method as in the original issue:
```
#
#
#
#
#
#
#
Aborted
```
To reproduce using a cross-compiled build:
```
<java> -XX:-UseCompressedOops -XX:+UseCompressedClassPointers -Xshare:dump -Xlog:cds* -version
<java> -XX:-UseCompressedOops -XX:+UseCompressedClassPointers -Xshare:on -XX:-TieredCompilation \
-Xlog:cds* -Xlog:gc+metaspace=info -jar renaissance-gpl-0.14.1.jar -r 1 movie-lens
```
The …
> 8296448: RISC-V: Fix temp usages of heapbase register killed by MacroAssembler::en/decode_klass_not_null

- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
This is another-half backport (RISC-V part only) of [JDK-8287425](https://bugs.openjdk.org/browse/JDK-8287425). The original patch is at [1].
This patch can interestingly fix an issue with async-profiler [2], and has been backported to JDK17/JDK11u. But when backporting to JDK17, the RISC-V part of this patch was dropped [3] since we did not have the RISC-V backend. Now that we have the RISC-V port of JDK17, the missing part needs a backport as well.
Tested on unmatched, hotspot tier1\~2 (fastdebug). More tiers are on the way.
[1] https://github.com/openjdk/jdk/commit/b5a646ee6cfd432cef6b7e69a177959227a38ace
[2] https://github.com/jvm-profiling-tools/async-profiler/issues/673#issuecomment-1316738564
[3] https://github.com/openjdk/jdk17u-dev/pull/672
---------
* …
> 8287425: Remove unnecessary register push for MacroAssembler::check_klass_subtype_slow_path

- src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
- src/hotspot/cpu/riscv/c1_MacroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
- src/hotspot/cpu/riscv/nativeInst_riscv.cpp
- src/hotspot/cpu/riscv/riscv.ad
- src/hotspot/cpu/riscv/sharedRuntime_riscv.cpp
May be not clean, for we do not have `C2CodeStub`.
Tested hotspot tier1~2 (fastdebug); other tiers are on the way.
---------
* [JDK-8294087](https://bugs.openjdk.org/browse/JDK-8294087): RISC-V: RVC: Fix a potential alignment issue and add more alignment assertions for the patchable calls/nops
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u pull/14/head:pull/14` \
`$ git checkout pull/14`
`$ git checkout pull/14` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u pull/14/head`
</details>
`$ git pr checkout 14`
`$ git pr show -t 14`
</details> …
> 8294087: RISC-V: RVC: Fix a potential alignment issue and add more alignment assertions for the patchable calls/nops

- src/hotspot/cpu/riscv/icache_riscv.cpp
- src/hotspot/os_cpu/linux_riscv/os_linux_riscv.hpp
Backport of [JDK-8291947](https://bugs.openjdk.org/browse/JDK-8291947). 
In the current version, https://bugs.openjdk.org/browse/JDK-8290840 has not been refactored, so the issues corresponding to the original issue do not exist. compared to the original patch, the icache_flush function is removed in a different location.
Testing:
---------
* [JDK-8291947](https://bugs.openjdk.org/browse/JDK-8291947): riscv: fail to build after JDK-8290840
* [Vladimir Kempik](https://openjdk.org/census#vkempik) (@VladimirKempik - **Reviewer**)
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u pull/15/head:pull/15` \ …
> 8291947: riscv: fail to build after JDK-8290840

- src/hotspot/cpu/riscv/assembler_riscv.cpp
- src/hotspot/cpu/riscv/assembler_riscv.hpp
- src/hotspot/cpu/riscv/compiledIC_riscv.cpp
- src/hotspot/cpu/riscv/globals_riscv.hpp
- src/hotspot/cpu/riscv/icache_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
- src/hotspot/cpu/riscv/nativeInst_riscv.hpp
- src/hotspot/cpu/riscv/sharedRuntime_riscv.cpp
- src/hotspot/os_cpu/linux_riscv/orderAccess_linux_riscv.hpp
Backport of [JDK-8291893](https://bugs.openjdk.org/browse/JDK-8291893).
The original patch cannot be directly applied because of the line number, but there are no other additional changes.
Testing:
---------
* [JDK-8291893](https://bugs.openjdk.org/browse/JDK-8291893): riscv: remove fence.i used in user space
* [Feilong Jiang](https://openjdk.org/census#fjiang) (@feilongjiang - no project role) ⚠️ Review applies to [0bec4f0a](https://git.openjdk.org/riscv-port-jdk17u/pull/13/files/0bec4f0a02429b33231da6fbaf8524ca8d492d02)
* [Vladimir Kempik](https://openjdk.org/census#vkempik) (@VladimirKempik - **Reviewer**) ⚠️ Review applies to …
> 8291893: riscv: remove fence.i used in user space

- src/hotspot/cpu/riscv/stubGenerator_riscv.cpp
Please review this backport of JDK-8296602 to jdk17u
This effectively unrolls copy memory loop offering significant perf improvement on real hw platforms. ( data are the same as in original commit) 
RISC-V only change, low risk for other platforms.
Testing: TBD.
thead rvb-ice c910
thead
```
Before ( copy8 only )
Benchmark (size) Mode Cnt Score Error Units
ArrayCopyObject.conjoint_micro 31 thrpt 25 6653.095 ± 251.565 ops/ms
ArrayCopyObject.conjoint_micro 63 thrpt 25 4933.970 ± 77.559 ops/ms
ArrayCopyObject.conjoint_micro 127 thrpt 25 3627.454 ± 34.589 ops/ms
ArrayCopyObject.conjoint_micro 2047 thrpt 25 368.249 ± 0.453 ops/ms
ArrayCopyObject.conjoint_micro 4095 thrpt 25 187.776 ± 0.306 ops/ms
ArrayCopyObject.conjoint_micro 8191 thrpt 25 94.477 ± 0.340 ops/ms
after ( with copy32 ) …
```
> 8296602: RISC-V: improve performance of copy_memory stub

- src/hotspot/cpu/riscv/vm_version_riscv.cpp
Backport of [JDK-8304293](https://bugs.openjdk.org/browse/JDK-8304293).
Let me show the IR changes before and after the modification:
`java -Xcomp -XX:TieredStopAtLevel=1 -XX:+PrintIR -version > C1.log`
before:
```
B3 (V) [33, 49] dom B1 pred: B1
empty stack
inlining depth 0
__bci__use__tid____instr____________________________________
33   1    a35    <instance 0x00000040c003c3b8 klass=java/util/concurrent/atomic/AtomicLong>
. 8    0    l42    a25.invokespecial(a35, l27, l4)
jdk/internal/misc/Unsafe.getAndAddLong(Ljava/lang/Object;JJ)J
41   1    a46    <instance 0x00000040c003c3c0 klass=java/util/concurrent/atomic/AtomicLong>
7    1    l53    1L
. 8    0    l54    a25.invokespecial(a46, l27, l53) …
```
> 8304293: RISC-V: JDK-8276799 missed atomic intrinsic support for C1

- src/hotspot/cpu/riscv/assembler_riscv.hpp
Backporting RVC-related patches. Applied cleanly.
Tested along with other patches, hotspot tier1\~4 with fastdebug build.
---------
* [JDK-8285711](https://bugs.openjdk.org/browse/JDK-8285711): riscv: RVC: Support disassembler show-bytes option
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/20/head:pull/20` \
`$ git checkout pull/20`
`$ git checkout pull/20` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git pull/20/head`
</details>
`$ git pr checkout 20`
`$ git pr show -t 20`
</details>
<details><summary>Using diff file</summary>
Download …
> 8285711: riscv: RVC: Support disassembler show-bytes option

- src/hotspot/cpu/riscv/riscv.ad
Please help review this backport to riscv-port-jdk17u.
Backport of [JDK-8297644](https://bugs.openjdk.org/browse/JDK-8297644). Applies cleanly.
The compilation failed before the modification as follows:
```
Creating support/modules_libs/java.base/server/libjvm.so from 975 file(s)
/home/zifeihan/riscv-port-jdk17u/src/hotspot/cpu/riscv/riscv.ad: In member function 'virtual void MachPrologNode::emit(CodeBuffer&, PhaseRegAlloc*) const':
/home/zifeihan/riscv-port-jdk17u/src/hotspot/cpu/riscv/riscv.ad:1351:7: error: invalid use of incomplete type 'class BarrierSetAssembler'
1351 |     bs->nmethod_entry_barrier(&_masm);
|       ^~
In file included from /home/zifeihan/riscv-port-jdk17u/src/hotspot/share/gc/shared/modRefBarrierSet.hpp:28,
from …
```
> 8297644: RISC-V: Compilation error when shenandoah is disabled

- src/hotspot/cpu/riscv/assembler_riscv.hpp
- src/hotspot/cpu/riscv/frame_riscv.hpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
- src/hotspot/cpu/riscv/nativeInst_riscv.cpp
- src/hotspot/cpu/riscv/riscv.ad
- src/hotspot/cpu/riscv/stubGenerator_riscv.cpp
- src/hotspot/cpu/riscv/templateInterpreterGenerator_riscv.cpp
- src/hotspot/os_cpu/linux_riscv/os_linux_riscv.cpp
Backport one Yadong's patch, which can cleanup some RVC things.
Tested along with other patches, hotspot tier1\~4 with fastdebug build.
---------
* [JDK-8285699](https://bugs.openjdk.org/browse/JDK-8285699): riscv: Provide information when hitting a HaltNode
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/21/head:pull/21` \
`$ git checkout pull/21`
`$ git checkout pull/21` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git pull/21/head`
</details>
`$ git pr checkout 21`
`$ git pr show -t 21`
</details>
<details><summary>Using diff …
> 8285699: riscv: Provide information when hitting a HaltNode

- src/hotspot/cpu/riscv/assembler_riscv.hpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
Backport one RVC-related patch (3rd, 8 in total). The remaining patches seem to be linear and cannot be submitted concurrently.
Tested along with remaining RVC patches, hotspot tier1~4 with fastdebug build.
---------
* [JDK-8294086](https://bugs.openjdk.org/browse/JDK-8294086): RISC-V: Cleanup InstructionMark usages in the backend
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/23/head:pull/23` \
`$ git checkout pull/23`
`$ git checkout pull/23` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git pull/23/head`
</details>
`$ git pr checkout 23` …
> 8294086: RISC-V: Cleanup InstructionMark usages in the backend

- src/hotspot/cpu/riscv/assembler_riscv.cpp
- src/hotspot/cpu/riscv/assembler_riscv.hpp
- src/hotspot/cpu/riscv/c1_CodeStubs_riscv.cpp
- src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
- src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.hpp
- src/hotspot/cpu/riscv/c2_safepointPollStubTable_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
Tested along with remaining patches, hotspot tier1~4 with fastdebug build.
---------
* [JDK-8294187](https://bugs.openjdk.org/browse/JDK-8294187): RISC-V: Unify all relocations for the backend into AbstractAssembler::relocate()
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/24/head:pull/24` \
`$ git checkout pull/24`
`$ git checkout pull/24` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git pull/24/head`
</details>
`$ git pr checkout 24`
`$ git pr show -t 24`
</details>
<details><summary>Using diff file</summary>
Download this PR as a diff …
> 8294187: RISC-V: Unify all relocations for the backend into AbstractAssembler::relocate()

- src/hotspot/cpu/riscv/assembler_riscv.hpp
- src/hotspot/cpu/riscv/globals_riscv.hpp
- src/hotspot/cpu/riscv/riscv.ad
- src/hotspot/cpu/riscv/riscv_b.ad
Backport of [JDK-8297715](https://bugs.openjdk.org/browse/JDK-8297715).
The original patch cannot be directly applied because of the line number, but there are no other additional changes.
The effect is that we could then optimize C2 JIT code for methods like (print with case `xml.validation` in SPECjvm2008):
Before:
```
03c     lhu  R28, [R11, #12]	# short, #@loadUS ! Field: com/sun/org/apache/xerces/internal/dom/NodeImpl.flags
040 +   andi  R7, R28, #2	#@andI_reg_imm
044 +   snez  R10, R7	#@convI2Bool
```
After:
```
03c     lhu  R28, [R11, #12]	# short, #@loadUS ! Field: com/sun/org/apache/xerces/internal/dom/NodeImpl.flags
040 +   bexti  R10, R28, #2	#@convI2Bool_andI_reg_immIpowerOf2
```
Testing:
- Tier1 passed without new failure on …
> 8297715: RISC-V: C2: Use single-bit instructions from the Zbs extension

- src/hotspot/cpu/riscv/riscv.ad
Backport of [JDK-8300109](https://bugs.openjdk.org/browse/JDK-8300109). Applies cleanly.
Testing:
---------
* [JDK-8300109](https://bugs.openjdk.org/browse/JDK-8300109): RISC-V: Improve code generation for MinI/MaxI nodes
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/25/head:pull/25` \
`$ git checkout pull/25`
`$ git checkout pull/25` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git pull/25/head`
</details>
`$ git pr checkout 25`
`$ …
> 8300109: RISC-V: Improve code generation for MinI/MaxI nodes

- src/hotspot/cpu/riscv/assembler_riscv.hpp
- src/hotspot/cpu/riscv/c1_MacroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/nativeInst_riscv.cpp
- src/hotspot/cpu/riscv/riscv.ad
- src/hotspot/cpu/riscv/sharedRuntime_riscv.cpp
One little difference: there is no `C2_MacroAssembler::emit_entry_barrier_stub` on JDK17.
Tested along with remaining patches, hotspot tier1\~4 with fastdebug build.
---------
* [JDK-8294366](https://bugs.openjdk.org/browse/JDK-8294366): RISC-V: Partially mark out incompressible regions
* [Feilong Jiang](https://openjdk.org/census#fjiang) (@feilongjiang - no project role) ⚠️ Review applies to [b3f970ad](https://git.openjdk.org/riscv-port-jdk17u/pull/28/files/b3f970ad62036ef2fd3cc497e087f7e5d5053d81)
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/28/head:pull/28` \
`$ git checkout pull/28`
`$ …
> 8294366: RISC-V: Partially mark out incompressible regions

- src/hotspot/cpu/riscv/assembler_riscv.hpp
Backport the trivial typo fix in the RVC description, mentioned in #28.
---------
* [JDK-8305112](https://bugs.openjdk.org/browse/JDK-8305112): RISC-V: Typo fix for RVC description
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/30/head:pull/30` \
`$ git checkout pull/30`
`$ git checkout pull/30` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git pull/30/head`
</details>
`$ git pr checkout 30`
`$ git pr show -t 30`
</details>
<details><summary>Using diff file</summary>
Download this PR as a diff file: \
<a …
> 8305112: RISC-V: Typo fix for RVC description

- src/hotspot/cpu/riscv/assembler_riscv.cpp
- src/hotspot/cpu/riscv/assembler_riscv.hpp
- src/hotspot/cpu/riscv/c1_CodeStubs_riscv.cpp
- src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
- src/hotspot/cpu/riscv/c1_Runtime1_riscv.cpp
- src/hotspot/cpu/riscv/c2_safepointPollStubTable_riscv.cpp
- src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.cpp
- src/hotspot/cpu/riscv/interp_masm_riscv.cpp
- src/hotspot/cpu/riscv/jniFastGetField_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
- src/hotspot/cpu/riscv/sharedRuntime_riscv.cpp
- src/hotspot/cpu/riscv/templateTable_riscv.cpp
Backport `8295110: RISC-V: Mark out relocations as incompressible`.
A little conflict is that we do not have the refactoring `8295270: RISC-V: Clean up and refactoring for assembler functions` on 17u.
Tested along with remaining patches, hotspot tier1\~4 with fastdebug build.
---------
* [JDK-8295110](https://bugs.openjdk.org/browse/JDK-8295110): RISC-V: Mark out relocations as incompressible
* [Feilong Jiang](https://openjdk.org/census#fjiang) (@feilongjiang - no project role)
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/29/head:pull/29` \
`$ git checkout pull/29`
`$ git checkout pull/29` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git …
> 8295110: RISC-V: Mark out relocations as incompressible

- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/riscv.ad
Backport `8295396: RISC-V: Cleanup useless CompressibleRegions`.
Tested along with remaining patches, hotspot tier1\~4 with fastdebug build.
---------
* [JDK-8295396](https://bugs.openjdk.org/browse/JDK-8295396): RISC-V: Cleanup useless CompressibleRegions
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/31/head:pull/31` \
`$ git checkout pull/31`
`$ git checkout pull/31` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git pull/31/head`
</details>
`$ git pr checkout 31`
`$ git pr show -t 31`
</details>
<details><summary>Using diff file</summary> …
> 8295396: RISC-V: Cleanup useless CompressibleRegions

- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
Backport `8299168: RISC-V: Fix MachNode size mismatch for MacroAssembler::_verify_oops*`.
Tested along with remaining patches, hotspot tier1\~4 with fastdebug build.
---------
* [JDK-8299168](https://bugs.openjdk.org/browse/JDK-8299168): RISC-V: Fix MachNode size mismatch for MacroAssembler::_verify_oops*
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/32/head:pull/32` \
`$ git checkout pull/32`
`$ git checkout pull/32` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git pull/32/head`
</details>
`$ git pr …
> 8299168: RISC-V: Fix MachNode size mismatch for MacroAssembler::_verify_oops*

- src/hotspot/cpu/riscv/globals_riscv.hpp
The last backported patch of RVC - to enable it by default.
Although, we don't have `UseRVA20U64` in jdk17, so I only made `UseRVC` true here. Looking forward to some opinions about it.
Tested hotspot tier1\~4 with fastdebug build.
---------
* [JDK-8305512](https://bugs.openjdk.org/browse/JDK-8305512): RISC-V: Enable RVC extension by default on supported hardware
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/33/head:pull/33` \
`$ git checkout pull/33`
`$ git checkout pull/33` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git pull/33/head`
</details>
<details><summary>Using Skara …
> 8305512: RISC-V: Enable RVC extension by default on supported hardware

- src/hotspot/cpu/riscv/assembler_riscv.cpp
- src/hotspot/cpu/riscv/assembler_riscv.hpp
- src/hotspot/cpu/riscv/c1_CodeStubs_riscv.cpp
- src/hotspot/cpu/riscv/c1_LIRAssembler_arraycopy_riscv.cpp
- src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
- src/hotspot/cpu/riscv/vtableStubs_riscv.cpp
Backport of [JDK-8290137](https://bugs.openjdk.org/browse/JDK-8290137). Applies cleanly.
Testing:
- Tier1-3 passed without new failure on unmacthed (release).
---------
* [JDK-8290137](https://bugs.openjdk.org/browse/JDK-8290137): riscv: small refactoring for add_memory_int32/64
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/34/head:pull/34` \
`$ git checkout pull/34`
`$ git checkout pull/34` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git pull/34/head`
</details>
Checkout this PR …
> 8290137: riscv: small refactoring for add_memory_int32/64

- src/hotspot/cpu/riscv/gc/shenandoah/shenandoahBarrierSetAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
Backport of [JDK-8293474](https://bugs.openjdk.org/browse/JDK-8293474).
The original patch cannot be directly applied because of https://github.com/openjdk/riscv-port-jdk17u/pull/32 , and there are no other additional changes.
Testing:
- Tier1-3 passed without new failure on unmacthed (release).
---------
* [JDK-8293474](https://bugs.openjdk.org/browse/JDK-8293474): RISC-V: Unify the way of moving function pointer
`$ git fetch https://git.openjdk.org/riscv-port-jdk17u.git pull/35/head:pull/35` \
`$ git checkout pull/35`
`$ git checkout pull/35` \
`$ git pull https://git.openjdk.org/riscv-port-jdk17u.git pull/35/head`
</details> …
> 8293474: RISC-V: Unify the way of moving function pointer

- src/hotspot/cpu/riscv/assembler_riscv.cpp
- src/hotspot/cpu/riscv/assembler_riscv.hpp
- src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
- src/hotspot/cpu/riscv/gc/shared/barrierSetNMethod_riscv.cpp
- src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
- src/hotspot/cpu/riscv/nativeInst_riscv.cpp
- src/hotspot/cpu/riscv/nativeInst_riscv.hpp
- src/hotspot/cpu/riscv/stubGenerator_riscv.cpp
- src/hotspot/cpu/riscv/templateTable_riscv.cpp
Backport of [JDK-8294430](https://bugs.openjdk.org/browse/JDK-8294430).
The original patch cannot be directly applied because jdk17u has no `emit_entry_barrier_stub`, which introduced with [JDK-8293007](https://bugs.openjdk.org/browse/JDK-8293007), and there are no other additional changes.
Testing:
- Tier1-3 passed without new failure on unmacthed (release).
---------
* [JDK-8294430](https://bugs.openjdk.org/browse/JDK-8294430): RISC-V: Small refactoring for movptr_with_offset
* [Feilong Jiang](https://openjdk.org/census#fjiang) (@feilongjiang - no project role)
`$ git fetch …
> 8294430: RISC-V: Small refactoring for movptr_with_offset
